---

# - name: "update and upgrade packages."
#   # become: yes
#   apk:
#     upgrade: yes
#     update_cache: yes


# - name: install dependencies
#   # become: yes
#   apk:
#     name: nodejs, npm, python3
#     state: latest
#     update_cache: yes

# - name: install pm2
#   # become: yes
#   npm:
#     name: pm2
#     global: yes
#     state: latest
    # production: yes

- name: "Install Python"
  become: true
  shell: |
    # sudo yum reinstall yum --noplugins -y
    # sudo yum update
    # sudo yum install epel-release
    # sudo yum -y install nodejs npm
    sudo yum install nodejs npm --enablerepo=epel
# - name: "install nodejs, npm"
#   become: true
#   raw: |
#     nvm install node
#     node -v

# - name: "Update/upgrade packages"
#   become: true
#   raw: test -e /usr/bin/python3 || (apt -y update && apt -y upgrade)
#   changed_when: false

# - name: "install nodejs, npm"
#   become: true
#   raw: test -e /usr/bin/python3 || (apt -y update && apt install -y nodejs npm)
#   changed_when: false

# - name: "Install pm2"
#   become: true
#   raw: test -e /usr/bin/python3 || (npm install pm2 -g)
#   changed_when: false

# - name: extract artifact
#   become: yes
#   unarchive:
#     src: files/artifact.tar.gz
#     dest: .

- name: "Start Server"
  become: true
  raw: |
    npm install pm2 -g
    npm install
    pm2 stop default
    pm2 start npm -- run start

# - name: "Start "
#   shell: |
#     npm install
#     pm2 stop default
#     pm2 start npm -- start
