---
- name: "Install dependencies"
  become: true
  shell: |
    sudo yum install -y gcc-c++ make 
    curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash - 
    sudo yum install -y nodejs npm
 

- name: extract artifact
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: "Start Server"
  become: true
  shell: |
    sudo npm i @nestjs/common@6.11.11
    sudo npm i @nestjs/core@6.11.11
    sudo npm i @nestjs/swagger@3.1.0
    sudo npm i @nestjs/platform-express@6.11.11
    sudo npm install pm2 -g
    sudo npm install --legacy-peer-deps
    sudo pm2 stop default
    sudo pm2 start npm -- run start
    sudo pm2 link zv5d0885y1ovrc1 rmm2h4dxo57hcvt
  



 