---
- name: "Install dependencies"
  become: true
  shell: |
    sudo yum install -y gcc-c++ make 
    curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash - 
    sudo yum install -y nodejs npm
    # sudo yum update

- name: extract artifact
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: "Start Server"
  become: true
  shell: |
    export ENVIRONMENT=production
    export NODE_ENV=production
    export TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    export TYPEORM_MIGRATIONS_DIR="./migrations"
    export TYPEORM_MIGRATIONS="./migrations/*.js"
    export TYPEORM_ENTITIES="./modules/domain/**/*.entity.js"
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_PORT="{{ lookup('env', 'TYPEORM_PORT') }}"
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    sudo npm install pm2 -g
    sudo npm install --legacy-peer-deps
    sudo pm2 stop default
    sudo pm2 start npm -- run start
  


# export ENVIRONMENT= production
#     export NODE_ENV= production
#     export TYPEORM_MIGRATIONS_DIR= "./migrations"
#     export TYPEORM_MIGRATIONS= "./migrations/*.js"
#     export TYPEORM_ENTITIES= "./modules/domain/**/*.entity.js"
 