---
- name: "Install Python"
  become: true
  raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python) 
  changed_when: false

- name: "Update/upgrade packages"
  become: true
  raw: test -e /usr/bin/python3 || (apt -y update && apt -y upgrade) 
  changed_when: false
  
- name: "install nodejs, npm"
  become: true
  raw: test -e /usr/bin/python3 || (apt -y update && apt install -y nodejs npm) 
  changed_when: false
  
- name: "Install pm2"
  become: true
  raw: test -e /usr/bin/python3 || ( npm i -g pm2) 
  changed_when: false


- name: "extract files" 
  become: true
  shell: |
    tar xzf artifact.tar.gz -C .

- name: "Start "
  shell: | 
    npm install
    pm2 stop default
    pm2 start npm -- start