---

- name: "Install dependencies"
  become: true
  shell: |
    sudo yum install -y gcc-c++ make 
    curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash - 
    sudo yum install -y nodejs npm

- name: extract artifact
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: "Start Server"
  become: true
  shell: |
    npm install pm2 -g
    npm install
    pm2 stop default
    pm2 start npm -- run start
