---
- name: "Install dependencies"
  become: true
  shell: |
    sudo yum install -y gcc-c++ make 
    curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash - 
    sudo yum install -y nodejs npm
    # sudo yum update

- name: extract artifact
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: "Start Server"
  become: true
  shell: |
    sudo npm install pm2 -g
    sudo npm install --legacy-peer-deps
    sudo pm2 stop default
    sudo pm2 start npm -- run start
  



 