---
- name: "Install Python"
  become: true
  apt:
    name:  python
    state: latest
    update_cache: yes

- name: 'Update/upgrade packages'
  become: yes
  apt:
    upgrade: yes

- name: "install nodejs, npm"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  npm:
    name: pm2
    global: yes

- name: "extract files" 
  become: true
  shell: |
    cd /home/ubuntu
    tar xzf artifact.tar.gz -C .

- name: "Start "
  shell: | 
    npm install
    pm2 stop default
    pm2 start npm -- start